# Generated by Django 3.1.4 on 2021-01-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='i_name',
            field=models.CharField(max_length=1000),
        ),
    ]
